language: python
python: 3.5
install: "pip install git+https://github.com/singingwolfboy/lektor.git@fix-ghpages-https-deploy#egg=lektor"
script: "lektor build"
deploy:
  provider: script
  script: "lektor deploy ghpages"
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds
